import { useMemo, useState } from "react";
import { Calculator, Check, ChevronDown, ChevronLeft, ChevronUp, Leaf, Minus, PackageCheck, Plus, Salad, Sparkles, Trash2, X } from "lucide-react";
import prepData from "@/prep_data.json";

const { dishes, categories, marinate_recipes: recipes } = prepData;
const MODULES = ["肉类模块", "主食模块", "蔬菜碗模块", "调味模块", "酱汁模块"];
const parse = (spec = "") => { const match = String(spec).match(/([\d.]+)\s*(g|份|根|颗)/); return spec === "/" ? { n: 0, unit: "" } : match ? { n: Number(match[1]), unit: match[2] } : { n: 1, unit: "份" }; };
const initial = (dish) => ({ id: crypto.randomUUID(), dish, quantity: 1, style: dish.has_styles ? dish.styles[0].style_name : "", choices: Object.fromEntries((dish.option_groups || []).map((group) => [group.group_name, group.items[0]?.name || ""])) });

export default function Index() {
  const [items, setItems] = useState([]); const [picker, setPicker] = useState(false); const [step, setStep] = useState("category"); const [category, setCategory] = useState(""); const [draft, setDraft] = useState(null); const [summaryOpen, setSummaryOpen] = useState(false); const [recipeId, setRecipeId] = useState(recipes[0].id); const [weight, setWeight] = useState(0);
  const selectedRecipe = recipes.find((recipe) => recipe.id === recipeId);
  const seasonings = useMemo(() => [...(selectedRecipe.extends ? recipes.find((recipe) => recipe.id === selectedRecipe.extends)?.seasonings || [] : []), ...selectedRecipe.seasonings], [selectedRecipe]);
  const summary = useMemo(() => { const result = Object.fromEntries([...MODULES, "香蕉"].map((key) => [key, {}])); const add = (group, value, count) => { if (!value || value.spec === "/") return; const { n, unit } = parse(value.spec); const target = result[group][value.name] || { n: 0, unit }; target.n += n * count; result[group][value.name] = target; }; items.forEach((item) => { const { dish, quantity, style, choices } = item; const modules = dish.has_styles ? dish.styles.find((value) => value.style_name === style)?.modules : dish.modules; Object.entries(modules || {}).forEach(([group, value]) => add(group, value, quantity)); (dish.option_groups || []).forEach((group) => add(group.group_name === "香蕉" ? "香蕉" : group.group_name, group.items.find((value) => value.name === choices[group.group_name]), quantity)); }); return result; }, [items]);
  const openPicker = () => { setPicker(true); setStep("category"); setCategory(""); setDraft(null); };
  const addDraft = () => { setItems((prev) => [...prev, draft]); setPicker(false); };
  const changeQty = (id, diff) => setItems((prev) => prev.map((item) => item.id === id ? { ...item, quantity: Math.max(1, item.quantity + diff) } : item));
  return <main className="min-h-screen bg-[#f5f7f4] text-slate-800"><header className="border-b border-emerald-900/10 bg-white"><div className="mx-auto flex max-w-6xl items-center gap-3 px-4 py-5"><div className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-600 text-white"><Leaf size={22} /></div><div><h1 className="text-lg font-bold text-slate-900">壮壮FIT 门店备料助手</h1><p className="text-sm text-slate-500">逐道添加菜品 · 自动汇总备料</p></div></div></header><div className="mx-auto grid max-w-6xl gap-6 px-4 py-6 lg:grid-cols-[1.45fr_.8fr]">
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-5"><div className="flex items-center gap-2"><Salad size={20} className="text-emerald-600" /><h2 className="font-bold">餐品备料助手</h2></div><p className="mt-1 text-sm text-slate-500">按顺序添加今日需要制作的菜品。</p></div><div className="min-h-56 space-y-3 p-4">{items.length ? items.map((item) => <AddedItem key={item.id} item={item} changeQty={changeQty} remove={() => setItems((prev) => prev.filter((value) => value.id !== item.id))} />) : <div className="flex min-h-48 flex-col items-center justify-center rounded-xl border border-dashed border-slate-300 bg-slate-50 text-center"><PackageCheck size={30} className="mb-3 text-slate-300" /><p className="font-semibold text-slate-600">暂无菜品</p><p className="mt-1 text-sm text-slate-400">点击下方按钮添加</p></div>}</div><div className="grid grid-cols-2 gap-3 border-t border-slate-100 p-4"><button onClick={openPicker} className="flex min-h-12 items-center justify-center gap-1 rounded-lg bg-emerald-600 font-semibold text-white"><Plus size={18} />添加菜品</button><button onClick={() => setItems([])} disabled={!items.length} className="min-h-12 rounded-lg bg-slate-200 font-semibold text-slate-700 disabled:opacity-40">完成并清空</button></div><div className="px-4 pb-4"><button onClick={() => setSummaryOpen(true)} disabled={!items.length} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-lg border border-emerald-600 font-semibold text-emerald-700 disabled:border-slate-200 disabled:text-slate-400"><Sparkles size={18} />生成备料清单</button></div></section>
    <CalculatorPanel recipeId={recipeId} setRecipeId={setRecipeId} weight={weight} setWeight={setWeight} recipe={selectedRecipe} seasonings={seasonings} /></div>{picker && <Picker step={step} setStep={setStep} category={category} setCategory={setCategory} draft={draft} setDraft={setDraft} close={() => setPicker(false)} add={addDraft} />}{summaryOpen && <Summary summary={summary} total={items.length} close={() => setSummaryOpen(false)} />}</main>;
}
function AddedItem({ item, changeQty, remove }) { const [expanded, setExpanded] = useState(false); const labels = [item.style, ...Object.values(item.choices)].filter(Boolean); const modules = item.dish.has_styles ? item.dish.styles.find((style) => style.style_name === item.style)?.modules : item.dish.modules; const selectedOptions = (item.dish.option_groups || []).map((group) => ({ group: group.group_name, value: group.items.find((choice) => choice.name === item.choices[group.group_name]) })).filter((entry) => entry.value); const toggle = () => setExpanded((value) => !value); return <article className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><button onClick={toggle} className="flex w-full items-start justify-between gap-3 p-4 text-left"><div className="min-w-0"><h3 className="font-semibold text-slate-800">{item.dish.name}</h3><p className="mt-1 truncate text-sm text-slate-500">{labels.join(" · ") || "默认配餐"}</p></div><span className="grid h-8 w-8 shrink-0 place-items-center rounded-md bg-slate-50 text-slate-500">{expanded ? <ChevronUp size={17} /> : <ChevronDown size={17} />}</span></button>{expanded && <div className="border-t border-emerald-100 bg-emerald-50/35 px-4 py-3"><p className="mb-2 text-xs font-bold tracking-wide text-emerald-800">完整模块明细（单份）</p><div className="space-y-1.5">{Object.entries(modules || {}).map(([group, value]) => <DetailRow key={group} group={group} value={value} />)}{selectedOptions.map((entry) => <DetailRow key={entry.group} group={entry.group} value={entry.value} />)}</div></div>}<div className="flex items-center justify-between border-t border-slate-100 px-4 py-3"><span className="text-sm text-slate-500">制作数量</span><div className="flex items-center gap-3"><button onClick={() => changeQty(item.id, -1)} className="grid h-9 w-9 place-items-center rounded-md border border-slate-300"><Minus size={16} /></button><b>{item.quantity}</b><button onClick={() => changeQty(item.id, 1)} className="grid h-9 w-9 place-items-center rounded-md border border-emerald-300 text-emerald-700"><Plus size={16} /></button><button onClick={remove} className="ml-1 grid h-9 w-9 place-items-center rounded-md text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={18} /></button></div></div></article>; }
function DetailRow({ group, value }) { return <div className="flex items-start justify-between gap-3 rounded-lg bg-white px-3 py-2 text-sm"><span className="text-slate-500">{group}</span><span className="text-right font-medium text-slate-700">{value.name}<span className="ml-1 text-emerald-700">{value.spec !== "/" ? `· ${value.spec}` : ""}</span></span></div>; }
function Picker({ step, setStep, category, setCategory, draft, setDraft, close, add }) { const chooseCategory = (value) => { setCategory(value); setStep("dish"); }; const chooseDish = (dish) => { setDraft(initial(dish)); setStep("config"); }; return <Modal title={step === "category" ? "选择品类" : step === "dish" ? category : "配置菜品"} close={close}>{step === "category" && <div className="grid gap-3 sm:grid-cols-3">{categories.map((value) => <button key={value} onClick={() => chooseCategory(value)} className="min-h-24 rounded-xl border border-emerald-200 bg-emerald-50 px-4 text-left font-bold text-emerald-800">{value}<span className="mt-1 block text-sm font-normal">{dishes.filter((dish) => dish.category === value).length} 款菜品</span></button>)}</div>}{step === "dish" && <div><button onClick={() => setStep("category")} className="mb-3 inline-flex items-center gap-1 text-sm text-slate-500"><ChevronLeft size={16} />返回品类</button><div className="space-y-2">{dishes.filter((dish) => dish.category === category).map((dish) => <button key={dish.name} onClick={() => chooseDish(dish)} className="flex min-h-12 w-full items-center justify-between rounded-lg border border-slate-200 px-4 text-left font-medium hover:border-emerald-400">{dish.name}<Plus size={17} className="text-emerald-600" /></button>)}</div></div>}{step === "config" && <Config draft={draft} setDraft={setDraft} cancel={() => setStep("dish")} add={add} />}</Modal>; }
function Config({ draft, setDraft, cancel, add }) { const groups = draft.dish.option_groups || []; const updateChoice = (key, value) => setDraft((prev) => ({ ...prev, choices: { ...prev.choices, [key]: value } })); return <div className="space-y-4"><button onClick={cancel} className="inline-flex items-center gap-1 text-sm text-slate-500"><ChevronLeft size={16} />返回菜品列表</button><h3 className="font-bold text-slate-900">{draft.dish.name}</h3>{draft.dish.has_styles && <div><p className="label">款式</p><div className="mt-2 flex gap-2">{draft.dish.styles.map((style) => <label key={style.style_name} className={`rounded-lg border px-4 py-2 text-sm ${draft.style === style.style_name ? "border-emerald-500 bg-emerald-50 text-emerald-800" : "border-slate-200"}`}><input className="sr-only" type="radio" checked={draft.style === style.style_name} onChange={() => setDraft((prev) => ({ ...prev, style: style.style_name }))} />{style.style_name}</label>)}</div></div>}<div className="grid gap-3 sm:grid-cols-2">{groups.map((group) => <label key={group.group_name} className="block text-sm font-semibold text-slate-600">{group.group_name}<select value={draft.choices[group.group_name]} onChange={(event) => updateChoice(group.group_name, event.target.value)} className="mt-1.5 h-12 w-full rounded-lg border border-slate-300 bg-white px-3 font-normal"><>{group.items.map((choice) => <option key={choice.name}>{choice.name}</option>)}</></select></label>)}</div><button onClick={add} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-emerald-600 font-semibold text-white"><Check size={18} />确认添加</button></div>; }
function CalculatorPanel({ recipeId, setRecipeId, weight, setWeight, recipe, seasonings }) { return <section className="h-fit rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-5"><div className="flex items-center gap-2"><Calculator size={20} className="text-amber-600" /><h2 className="font-bold">调料计算助手</h2></div><p className="mt-1 text-sm text-slate-500">按食材实际重量等比例换算配方。</p></div><div className="space-y-5 p-5"><div><p className="label">腌制类型</p><div className="mt-2 space-y-2">{recipes.map((value) => <label key={value.id} className={`flex min-h-11 items-center gap-2 rounded-lg border px-3 text-sm ${recipeId === value.id ? "border-emerald-500 bg-emerald-50" : "border-slate-200"}`}><input type="radio" checked={recipeId === value.id} onChange={() => setRecipeId(value.id)} className="accent-emerald-600" />{value.name}</label>)}</div></div><div><p className="label">食材重量（克）</p><input type="number" min="0" value={weight || ""} onChange={(event) => setWeight(Number(event.target.value))} placeholder={`基准 ${recipe.base_weight_g}g`} className="mt-2 h-12 w-full rounded-lg border border-slate-300 px-3" /></div><div className="rounded-xl bg-amber-50 p-4"><div className="mb-3 flex justify-between"><b>调料用量</b><span className="text-xs text-slate-500">基准 {recipe.base_weight_g}g</span></div>{weight > 0 ? <ul className="space-y-2">{seasonings.map((value) => <li key={value.name} className="flex justify-between border-b border-amber-100 pb-2 text-sm last:border-0"><span>{value.name}</span><b className="text-amber-700">{(weight / recipe.base_weight_g * value.base_amount_g).toFixed(1)}g</b></li>)}</ul> : <p className="text-sm text-slate-500">输入重量后显示计算结果</p>}</div></div></section>; }
function Summary({ summary, total, close }) { return <Modal title="备料清单" close={close}><p className="mb-4 text-sm text-emerald-700">已汇总 {total} 道已添加菜品</p><div className="grid gap-4 sm:grid-cols-2">{[...MODULES, "香蕉"].map((group) => <section key={group} className="rounded-xl bg-slate-50 p-3.5"><h3 className="mb-2 text-sm font-bold">{group === "香蕉" ? "香蕉汇总" : group}</h3>{Object.entries(summary[group]).length ? <ul className="space-y-2">{Object.entries(summary[group]).map(([name, value]) => <li key={name} className="flex justify-between rounded-lg bg-white px-3 py-2 text-sm"><span>{name}</span><b className="text-emerald-700">{value.n}{value.unit}</b></li>)}</ul> : <p className="text-sm text-slate-400">暂无</p>}</section>)}</div></Modal>; }
function Modal({ title, close, children }) { return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/40 p-4"><section className="mx-auto my-5 w-full max-w-2xl rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-emerald-100 bg-emerald-50 px-5 py-4"><h2 className="font-bold text-slate-900">{title}</h2><button onClick={close} className="grid h-10 w-10 place-items-center rounded-lg text-slate-500"><X size={20} /></button></div><div className="p-5">{children}</div></section></div>; }
